Tomek Pany
skrafi/git pull request #2
Opened 2019-05-21 15:53 UTC by TomaszMandel

comment

2019-05-21 15:54 UTC, kamilakli requested changes
no chyba nie

2019-05-21 15:55 UTC, kamilakli requested changes

2019-05-21 15:55 UTC, kamilakli commented on README.md
> -# gitkamila
jak możesz usuwać

2019-05-22 13:10 UTC, TomaszMandel commented on README.md
> -# gitkamila
Fikset, riwju egen if you umysł

2019-05-22 13:21 UTC, merged